name: lint
on:
  pull_request:
    branches:
      - "master"
      - "rolling"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4

      - name: Use luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: make lint-lua

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./utils"
          ignore: "bin"
